### ISSUE TITLE
basic/test_wg_barrier fails on CL 3.0 with CL C 1.2

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/OpenCL-CTS#1035]
In my current CL 3.0 implementation the stack only advertises CL C 1.2 support.

This test never checks for that though and fails when it tries to use work_group_barrier which is only introduced in CL 2.0.

Is the correct behaviour here to detect that and skip the test?

**Comment by FranklandJack** [comment]
Hi, thanks for your issue.

When you say:
> In my current CL 3.0 implementation the stack only advertises CL C 1.2 support.

can I ask how this is being reported? Is it via a `clGetDeviceInfo` query with [CL_DEVICE_OPENCL_C_VERSION](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_OPENCL_C_VERSION) since this would only report the latest fully backwards compatible version which could well be OpenCL C 1.2.

From  [CL_DEVICE_OPENCL_C_ALL_VERSIONS](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_OPENCL_C_ALL_VERSIONS) the spec says that:
> Because OpenCL 3.0 is backwards compatible with OpenCL C 1.2, and OpenCL C 1.2 is backwards compatible with OpenCL C 1.1 and OpenCL C 1.0, support for at least OpenCL C 3.0, OpenCL C 1.2, OpenCL C 1.1, and OpenCL C 1.0 is required for an OpenCL 3.0 device.

So I believe **OpenCL C 3.0 support is required for an OpenCL 3.0 device**, in which case the test shouldn't be skipped and `work_group_barrier` would need to be implemented on this device.

**Comment by airlied** [comment]
I read that 3 times yesterday and once more this morning and still missed it. Sorry for the noise, and for enlightenment.
