### ISSUE TITLE
"-cl-std=CL2.0" build option may not be supported on OpenCL3.0 devices

### ISSUE THREAD

**Issue by lengleng1992** [KhronosGroup/OpenCL-CTS#1380]
https://github.com/KhronosGroup/OpenCL-CTS/blob/06415f8b79c38bb08279c8267d38b41101f32760/test_conformance/basic/test_progvar.cpp#L27

Hi! @FranklandJack @bashbaug 

Considering that some OpenCL3.0 devices can support PSGV as a optional feature, but do not support all OpenCL2.0 core features. 
Therefore, if "-cl-std=CL2.0" is used, clBuildProgram may return CL_INVALID_BUILD_OPTIONS.
I think here need to use "-cl-std=CL3.0" instead of "-cl-std=CL2.0" on OpenCL3.0 device.

The similar problem also found in test_generic_address_space

https://github.com/KhronosGroup/OpenCL-CTS/blob/06415f8b79c38bb08279c8267d38b41101f32760/test_conformance/generic_address_space/advanced_tests.cpp#L110

Best Regards~

**Comment by FranklandJack** [comment]
Hey! Thanks for the issue. 

Since our 3.0 implementation doesn't support program scope global variables or the generic address space feature, we haven't run into this issue, but it does sound like a patch is required. I think the best thing to do here is to detect the latest CL C version supported by the device and use that as the build option string passed to any compile/build APIs.

I'm not particularly familiar with the tests in either [test_progvar.cpp](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/basic/test_progvar.cpp) or [advanced_tests.cpp](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/generic_address_space/advanced_tests.cpp)  but I notice they make use of the [create_single_kernel_helper_with_build_options](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/kernelHelpers.cpp#L747) wrapper, which takes an optional `buildOptions` parameter. When `buildOptions` is `nullptr` this wrapper does what I've described above and selects the most recent CL C supported by all devices in the context, so replacing `OPTIONS` with with `nullptr` in these invocations should get us some of the way for free.

In [test_progvar.cpp](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/basic/test_progvar.cpp)  It looks like `OPTIONS` is also passed to calls to `create_single_kernel_helper_create_program`, `clCompileProgram` and `clBuildProgram` so these will need to be passed the latest CL C supported by the device. There is already a helper function to do this: [get_device_latest_cl_c_version](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/kernelHelpers.cpp#L1636), so calling that with the device and passing the result to these API should work.

In [advanced_tests.cpp](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/generic_address_space/advanced_tests.cpp)  it looks like there are calls to `clCompileProgram` with a `-cl-std=CL2.0` string literal for the options argument, so we could do the same thing here and call  [get_device_latest_cl_c_version](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_common/harness/kernelHelpers.cpp#L1636) passing the result to the build options parameter of the API.

Pull requests are always welcome, so if you'd like to open one for this I'll make sure to review it :)

**Comment by svenvh** [comment]
Closing as this should be fixed by #1710
