### ISSUE TITLE
Many in-tree SPIR-V files don't pass the validator

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#22]

**Comment by StuartDBrady** [comment]
Most of these have been fixed by PR #272 and PR #472 (and possibly also by fixes to the SPIR-V validator).

I have raised issue 3322 in the SPIRV-Tools repository against the remaining validation failure in decorate_nonwritable.spvasm32, decorate_nonwritable.spvasm64. Provided it is accepted that this is a bug in the SPIR-V validator, and not in the tests, this issue can be closed.

**Comment by StuartDBrady** [comment]
It has been determined that the SPIR-V validator was correct in reporting a validation failure in decorate_nonwritable.spv\*, and that it currently fails to report validation failures in decorate_nonreadable.spv\*, decorate_coherent.spv\* and  decorate_volatile.spv\*. As such, I have raised PR #958 to remove these.

**Comment by kpet** [comment]
@StuartDBrady Isn't this now fixed?

**Comment by StuartDBrady** [comment]
@kpet, yes, this is fixed.
