### ISSUE TITLE
 supporting “cl_khr_create_command_queue” extension,

### ISSUE THREAD

**Issue by elitchang** [KhronosGroup/OpenCL-CTS#4]
Hi,
Is it possible that enable support " cl_khr_create_command_queue” extension in bellow code path ? 
test_conformance/compiler/test_compiler_defines_for_extensions.cpp
![known_extnsions](https://user-images.githubusercontent.com/16602971/45006203-4c4c8b80-b02a-11e8-9b38-b3e5c6316c67.png)

**Comment by kpet** [comment]
Thanks for the report and sorry for the very long delay to get a reply. This has already been fixed in the members-only repository. We're in the process of moving all further development on the conformance tests (except when related to unreleased specifications) to Github to make it easier to interact with the community. The fix should make its way into Github soon. Feel free to submit a pull request with a change if you need it earlier. Also feel free to create issues for any other problems you might be encountering.

**Comment by kpet** [comment]
This is now fixed in `cl12_trunk`, closing.
