### ISSUE TITLE
Required Read and Write Image Formats Untested

### ISSUE THREAD

**Issue by Jeremy-Kemp** [KhronosGroup/OpenCL-CTS#639]
Currently, `check_minimum_supported` only checks for read _or_ write formats. There is no checking for read _and_ write.

Conformance should be updated to check for this.

Inspired by: https://github.com/KhronosGroup/OpenCL-CTS/pull/629#pullrequestreview-367266392

**Comment by Jeremy-Kemp** [comment]
Duplicate of #427

**Comment by kpet** [comment]
In addition to adding read and write formats to `check_minimum_supported`, we also need to change the `clGetInfo` test to validate the list of read and write formats. I'm fine with tacking that to #427 if that's the preference but we should capture the need to do that explicitly.

**Comment by bashbaug** [comment]
I believe there is action required here for OpenCL 3.0 full profile devices.  Although "read-and-write" images are optional in OpenCL 3.0, we do define a minimum set of required image formats for full profile OpenCL 3.0 if read-and-write images are supported - see Table 20 in the [spec](https://bashbaug.github.io/OpenCL-Docs/html/OpenCL_API.html#minimum-list-of-supported-image-formats).

We can add these checks in several ways:

1. We can extend the `clGetInfo` test to validate read and write images in addition to read-only and write-only images.  This is a bit of a heavier-weight test, since it could (should?) validate image creation and queries in addition to validating image formats.

2. We could add checks in the API feature consistency test for read-write images.

3. We could move all of the image format checks out of the `clGetInfo` test and into a specific "image formats" API test, similar to the "min_max" tests.

(3) feels the cleanest to me, though it is a bit of a bigger change.  I don't think I'd do (2) since it feels like a bit of a hack and it's not much less work than (3).  Does anyone want to advocate strongly for (1)?  If not, I'll get started on (3) - probably tomorrow (Wednesday).

**Comment by kpet** [comment]
Good thing we checked :).

There's no good reason for the required format tests to be done as part of `clGetInfo`. These are two different tests. I agree (3) is the way to go. This also highlights a few additional issues that we ought to capture:
- read -and-write images are not covered in `clGetInfo`
- `clGetInfo` 1D/2D/3D tests are almost duplicates and can be merged.

**Comment by neiltrevett** [comment]
Issues 639 427 – should be looked at together
