### ISSUE TITLE
is_extension_available does not work for the last supported extension

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/OpenCL-CTS#790]
The `std::string` returned by `get_device_info_string()` contains the ending null character from the C-string returned by `clGetDeviceInfo()`.

This means that `is_extension_available()` will always fail for the last supported extension as [`found`](https://github.com/KhronosGroup/OpenCL-CTS/blob/09aa54246f607bc1770a7cc2dc076185487a00f7/test_common/harness/deviceInfo.cpp#L59) will contain `"extension_name\0"` while the temporary `std::string` created on [line 60](https://github.com/KhronosGroup/OpenCL-CTS/blob/09aa54246f607bc1770a7cc2dc076185487a00f7/test_common/harness/deviceInfo.cpp#L60) from `extensionName` will contain `"extension_name"`.

* One fix could be to change [`return std::string(info.begin(), info.end());`](https://github.com/KhronosGroup/OpenCL-CTS/blob/09aa54246f607bc1770a7cc2dc076185487a00f7/test_common/harness/deviceInfo.cpp#L48) into `return std::string(info.data());` as it will not copy over the null character, but it will also stop at the first null character which might not be desirable in some scenarios (for example if `clGetDeviceInfo()` returns something like `"str0\0str1\0str2\0\0"`, but I don’t think it is ever the case).
* Another solution would be to modify `get_device_extensions_string()` (and `get_device_il_version_string()`) to trim out the null character before returning the string to the caller.

**Comment by bashbaug** [comment]
I think this was fixed by #912.  Specifically, see the discussion [here](https://github.com/KhronosGroup/OpenCL-CTS/pull/912#pullrequestreview-479946807).  I've gone through all of the extensions in our extension string and they are behaving as expecting, even the last one, and even with extra whitespace before and after the last extension.

@pierremoreau , since I believe this issue is fixed I am closing it, but please feel free to reopen it if we need to take another look.  Thanks!

**Comment by pierremoreau** [comment]
Yes, I can confirm that this has now been fixed. Thank you for taking care of it!
